name: Terraform MCP Review

on:
  pull_request:
    paths:
      - '**/*.tf'
  push:
    branches:
      - main
    paths:
      - '**/*.tf'

jobs:
  analyze-terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Terraform + Python deps
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl gnupg software-properties-common
          curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o hashicorp.gpg
          sudo install -o root -g root -m 644 hashicorp.gpg /etc/apt/trusted.gpg.d/
          echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install terraform -y
          pip install requests

      - name: Run Terraform static checks
        run: |
          terraform init
          terraform validate
          terraform fmt -check
          terraform plan -no-color > plan.txt || true

      - name: Compute Git Diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }} > diff.patch

      - name: Submit to MCP server
        run: python3 submit_to_mcp.py
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.repository }}

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: review.md
